export const FETCH_PRODUCTS_REQUEST = 'app/HomePage/FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'app/HomePage/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'app/HomePage/FETCH_PRODUCTS_FAILURE';
