// TODO: exportRows only used by DataTable, thus, it should be moved there

export const EXPORT_REQUEST = 'app/App/EXPORT_REQUEST';
export const EXPORT_SUCCESS = 'app/App/EXPORT_SUCCESS';
export const EXPORT_FAILURE = 'app/App/EXPORT_FAILURE';
export const SET_EXPORTING_PARAMS = 'app/App/SET_EXPORTING_PARAMS';

export const MAKE_FULL_REPORT_REQUEST = 'app/App/MAKE_FULL_REPORT_REQUEST';
export const MAKE_FULL_REPORT_SUCCESS = 'app/App/MAKE_FULL_REPORT_SUCCESS';
export const MAKE_FULL_REPORT_FAILURE = 'app/App/MAKE_FULL_REPORT_FAILURE';

export const MAKE_SUMMARY_REPORT_REQUEST = 'app/App/MAKE_SUMMARY_REPORT_REQUEST';
export const MAKE_SUMMARY_REPORT_SUCCESS = 'app/App/MAKE_SUMMARY_REPORT_SUCCESS';
export const MAKE_SUMMARY_REPORT_FAILURE = 'app/App/MAKE_SUMMARY_REPORT_FAILURE';
